### ISSUE TITLE
Connection to Portainer Server Failed! 

### ISSUE THREAD

**Issue by jcquiles** [SavageSoftware/portainer-backup#3]
Hello, 

When trying to install the Portainer backup via Docker I am getting the following error messages. Im not quite clear on what I might be needing to correct or double check here. Any advice would help. Thank you! 

Here is the errors and a screenshot of what im seeing.

` ✖ Connection to portainer server failed!` 

`│ ✖ -------------------------- ERROR -------------------------- ✖  │
├──┤
│ ERROR MESSAGE │ getaddrinfo ENOTFOUND portainer`

`Initializing operation             : ✔ TEST
Validating target backup directory : ✔ EXISTS → /backup
Validating target backup file      : ✔ DRYRUN → portainer-backup.tar.gz
Validating portainer server        : ✖ http://portainer:9000`

[gminadak](https://github.com/gminadak)
[savageautomate](https://github.com/SavageSoftware/portainer-backup/commits?author=savageautomate)

**Comment by jcquiles** [comment]
[gminadak](https://github.com/gminadak)

**Comment by savageautomate** [comment]
@jcquiles 

Basically, the container can't resolve the hostname "`portainer`" used in the address: http://portainer:9000
Depending on how you have the container instance configured it may not be able to access your DHCP server likely a service provided by your network router.   Try using the IP address of your portainer server rather than the hostname "portainer".  

Thanks, Robert

**Comment by savageautomate** [comment]
@jcquiles 

> ... if my portainer environment goes down, are these files I can import into a new Portainer environment and get my config file up and running again?

**YES!**    
Use the "[Restoring From Local File](https://docs.portainer.io/v/ce-2.9/admin/settings#restoring-from-a-local-file)" option on a new Portainer installation:  See:  
https://docs.portainer.io/v/ce-2.9/admin/settings#restoring-from-a-local-file

I would highly suggest testing it to make sure it is working as you expect.  Maybe bring up a test Portainer instance and just try the restore process. 

> Also, the containers I am working with in Portainer aren't currently stored in a Hub or Repo, does Portainer backup, backup the containers as well or what would you recommend?

**Not exactly.**
The Portainer backup does not store container images.  It's only backing up your Portainer configuration and stacks.  So if you define all your containers in stacks (_via docker-compose.yml files_) and the container images can be accessed via either a public or private container repository, then yes, restoring Portainer from backup and then re-deploying each stack would get you back up and running from scratch.  (assuming any container persistent data is stored using docker volumes on some persistent storage device like a NAS).  

Note, there is also an option to copy the individual stack files (`*.yml`) as named stack files independent from the  `portainer-backup.tar.gz` file.  I find this useful because if I need to restore a single stack, I can easily find it via its stack file name opposed to trying to crack open the `portainer-backup.tar.gz` and trying to find it via its obsfucated internal name.  Then I can just manually copy the stack YAML text and paste it into the Portainer stacks web UI.  
Below is my configuration for my portainer-backup instance with the stacks option enabled.

```
 environment:
      TZ: America/New_York
      PORTAINER_BACKUP_URL: "*********************"
      PORTAINER_BACKUP_TOKEN: "**************************"
      PORTAINER_BACKUP_PASSWORD: ""
      PORTAINER_BACKUP_OVERWRITE: 1
      PORTAINER_BACKUP_MKDIR: 1
      PORTAINER_BACKUP_SCHEDULE: "0 0 0 * * *"
      PORTAINER_BACKUP_STACKS: 1
      PORTAINER_BACKUP_DRYRUN: 0
      PORTAINER_BACKUP_CONCISE: 1
      PORTAINER_BACKUP_DIRECTORY: "/backup/{{ISO_DATE}}"
      PORTAINER_BACKUP_FILENAME: "portainer-backup.tar.gz"
```

Thanks, Robert
